#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000
# PROJ_DIR=$(pwd)
# echo "@hourly "$PROJ_DIR"manage.py runjobs hourly" > cronojobs.txt
#echo "@hourly manage.py deal_job" > cronojobs.txt
#/usr/bin/crontab cronojobs.txt
