# Generated by Django 2.0.8 on 2018-10-19 16:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20181017_0829'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Deals',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='JunkPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='companies.Contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Junk point',
                'verbose_name_plural': 'Junk points',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='JunkPointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(max_length=512, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Junk point type',
                'verbose_name_plural': 'Junk point types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(max_length=512, verbose_name='Description')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash', to='junk.Deal', verbose_name='Deal')),
            ],
            options={
                'verbose_name': 'Trash',
                'verbose_name_plural': 'Trash',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TrashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Trash type',
                'verbose_name_plural': 'Trash type',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='trash',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='junk.TrashType', verbose_name='Trash type'),
        ),
        migrations.AddField(
            model_name='junkpoint',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='junk.JunkPointType', verbose_name='Junk point'),
        ),
        migrations.AddField(
            model_name='deal',
            name='junk_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='junk.JunkPoint', verbose_name='Junk point'),
        ),
        migrations.AddField(
            model_name='deal',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Rider'),
        ),
    ]
