# Generated by Django 2.0.8 on 2018-10-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0003_auto_20181017_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ('id',), 'verbose_name': 'Deals'},
        ),
        migrations.AlterModelOptions(
            name='trash',
            options={'ordering': ('id',), 'verbose_name': 'Trash', 'verbose_name_plural': 'Trash'},
        ),
    ]
