# Generated by Django 2.0.8 on 2018-10-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("junk", "0004_auto_20181017_0831")]

    operations = [
        migrations.AlterModelOptions(
            name="trashtype",
            options={
                "ordering": ("id",),
                "verbose_name": "Trash type",
                "verbose_name_plural": "Trash type",
            },
        )
    ]
