# Generated by Django 2.0.8 on 2018-11-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0014_auto_20181120_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='junk_point',
        ),
    ]
