# Generated by Django 2.0.8 on 2018-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0016_auto_20181127_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junkpoint',
            name='types',
            field=models.ManyToManyField(to='junk.JunkPointType', verbose_name='Junk point type'),
        ),
    ]
