# Generated by Django 2.0.8 on 2018-10-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('id',), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('id',), 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
    ]
