# Generated by Django 2.0.8 on 2018-10-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
    ]
