# Generated by Django 2.0.8 on 2018-10-19 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_auto_20181017_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='dificulty',
        ),
        migrations.AddField(
            model_name='mission',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
    ]
