# Generated by Django 2.0.8 on 2018-10-17 08:27

from django.db import migrations
import ecojunk.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ecojunk.users.models.UserManager()),
            ],
        ),
    ]
