# Generated by Django 2.0.8 on 2018-10-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20181017_0827")]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "ordering": ("id",),
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("date_joined",),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
