# Generated by Django 2.0.8 on 2018-11-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181017_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='rol',
            field=models.CharField(choices=[('user', 'User'), ('rider', 'Rider')], max_length=255, verbose_name='Rol'),
        ),
    ]
