# Generated by Django 2.0.8 on 2018-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181113_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(default='user', to='users.Permission', verbose_name='Permissions'),
        ),
    ]
